name: CI/CD Pipeline
run-name: CI/CD Pipeline
on:
  workflow_dispatch:
  push:
jobs:
  Build-Test-Publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Build
        run: docker build --tag build --target build .
      - name: Test
        run: |
            docker build --tag test-runner --target test-runner .
            docker run --volume /var/run/docker.sock:/var/run/docker.sock test-runner \
                dotnet test --configuration Release --no-build --logger trx
      - name: Publish
        run: docker build --tag cicd --target runtime .

